added erc 721 example.
pactus-project/kelk pull request #50
Opened 2023-01-27 08:24 UTC by yenkhoon

## Description

Added erc 721 example

## Related issue(s)
#44

## Checklist

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] CHANGELOG is updated.

2023-01-27 08:24 UTC, yenkhoon commented
don't merge yet i am fixing some error.

2023-01-27 10:10 UTC, yenkhoon commented
burn function have not supported as issue #51

2023-01-31 16:17 UTC, b00f requested changes

2023-01-31 16:17 UTC, b00f commented on examples/erc721/src/contract.rs
> +process executes the contract associated with the addr with the given input as
```suggestion
process executes the contract with the given `msg` as
```

2023-01-31 16:17 UTC, b00f commented on examples/erc721/src/contract.rs
> +query executes the contract associated with the addr with the given input
```suggestion
query executes the contract with the given `msg`
```

2023-01-31 16:17 UTC, b00f commented on examples/erc721/src/erc721.rs
> +        let balance = self.balances.find(addr).unwrap().unwrap_or(0);
```suggestion
        let balance = self.balances.find(addr)?.unwrap_or(0);
```

2023-01-31 16:17 UTC, b00f commented on examples/erc721/src/erc721.rs
> +        let owner = self.owners.find(token_id).unwrap();
```suggestion
        let owner = self.owners.find(token_id)?;
```

2023-02-22 03:52 UTC, b00f approved these changes

2023-02-22 03:52 UTC, merged